# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180704_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=200)),
                ('hoster', models.CharField(max_length=100)),
                ('assignees', models.ManyToManyField(blank=True, related_name='issue_assignees', to='data.Contributor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to='data.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='IssueNumber',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('repo', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('ci_status', models.BooleanField()),
                ('hoster', models.CharField(max_length=100)),
                ('assignees', models.ManyToManyField(blank=True, related_name='mr_assignees', to='data.Contributor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mr_author', to='data.Contributor')),
                ('closes_issues', models.ManyToManyField(blank=True, to='data.IssueNumber')),
                ('labels', models.ManyToManyField(blank=True, to='data.Label')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='data.Label'),
        ),
    ]
