"""
This module contains the points assigned to the activity
variables, which will be used throughout the gamification
system.
"""

# Assigning points to the issues' activities
NEWCOMER_DIFFICULTY_BUG_ISSUE = 5
NEWCOMER_DIFFICULTY_LOW_IMPORTANCE_ISSUE = 5
NEWCOMER_DIFFICULTY_MEDIUM_IMPORTANCE_ISSUE = 5
NEWCOMER_DIFFICULTY_HIGH_IMPORTANCE_ISSUE = 5
NEWCOMER_DIFFICULTY_CRITICAL_IMPORTANCE_ISSUE = 5
NEWCOMER_DIFFICULTY_BUG_ISSUE = 5
NEWCOMER_DIFFICULTY_DOCUMENTATION_ISSUE = 5
NEWCOMER_DIFFICULTY_FEATURE_ISSUE = 5
LOW_DIFFICULTY_BUG_ISSUE = 5
LOW_DIFFICULTY_LOW_IMPORTANCE_ISSUE = 5
LOW_DIFFICULTY_MEDIUM_IMPORTANCE_ISSUE = 5
LOW_DIFFICULTY_HIGH_IMPORTANCE_ISSUE = 5
LOW_DIFFICULTY_FEATURE_ISSUE = 5
LOW_DIFFICULTY_CRITICAL_IMPORTANCE_ISSUE = 5
LOW_DIFFICULTY_DOCUMENTATION_ISSUE = 5
LOW_DIFFICULTY_BUG_ISSUE = 5
MEDIUM_DIFFICULTY_BUG_ISSUE = 5
MEDIUM_DIFFICULTY_LOW_IMPORTANCE_ISSUE = 5
MEDIUM_DIFFICULTY_MEDIUM_IMPORTANCE_ISSUE = 5
MEDIUM_DIFFICULTY_HIGH_IMPORTANCE_ISSUE = 5
MEDIUM_DIFFICULTY_CRITICAL_IMPORTANCE_ISSUE = 5
MEDIUM_DIFFICULTY_DOCUMENTATION_ISSUE = 5
MEDIUM_DIFFICULTY_FEATURE_ISSUE = 5
HIGH_DIFFICULTY_BUG_ISSUE = 5
HIGH_DIFFICULTY_LOW_IMPORTANCE_ISSUE = 5
HIGH_DIFFICULTY_MEDIUM_IMPORTANCE_ISSUE = 5
HIGH_DIFFICULTY_HIGH_IMPORTANCE_ISSUE = 5
HIGH_DIFFICULTY_CRITICAL_IMPORTANCE_ISSUE = 5
HIGH_DIFFICULTY_FEATURE_ISSUE = 5
NATIVE_BEAR_ISSUE = 5
LINTER_BEAR_ISSUE = 5
GENERIC_BEAR_ISSUE = 5
DUPLICATE_ISSUE = 5
INVALID_ISSUE = 5

# Assigning points to the prs' activities
NEWCOMER_DIFFICULTY_BUG_MR = 5
NEWCOMER_DIFFICULTY_LOW_IMPORTANCE_MR = 5
NEWCOMER_DIFFICULTY_MEDIUM_IMPORTANCE_MR = 5
NEWCOMER_DIFFICULTY_HIGH_IMPORTANCE_MR = 5
NEWCOMER_DIFFICULTY_CRITICAL_IMPORTANCE_MR = 5
NEWCOMER_DIFFICULTY_DOCUMENTATION_MR = 5
NEWCOMER_DIFFICULTY_FEATURE_MR = 5
LOW_DIFFICULTY_FEATURE_MR = 5
LOW_DIFFICULTY_BUG_MR = 5
LOW_DIFFICULTY_LOW_IMPORTANCE_MR = 5
LOW_DIFFICULTY_MEDIUM_IMPORTANCE_MR = 5
LOW_DIFFICULTY_HIGH_IMPORTANCE_MR = 5
LOW_DIFFICULTY_DOCUMENTATION_MR = 5
LOW_DIFFICULTY_CRITICAL_IMPORTANCE_MR = 5
MEDIUM_DIFFICULTY_BUG_MR = 5
MEDIUM_DIFFICULTY_LOW_IMPORTANCE_MR = 5
MEDIUM_DIFFICULTY_MEDIUM_IMPORTANCE_MR = 5
MEDIUM_DIFFICULTY_HIGH_IMPORTANCE_MR = 5
MEDIUM_DIFFICULTY_DOCUMENTATION_MR = 5
MEDIUM_DIFFICULTY_FEATURE_MR = 5
MEDIUM_DIFFICULTY_CRITICAL_IMPORTANCE_MR = 5
HIGH_DIFFICULTY_LOW_IMPORTANCE_MR = 5
HIGH_DIFFICULTY_MEDIUM_IMPORTANCE_MR = 5
HIGH_DIFFICULTY_HIGH_IMPORTANCE_MR = 5
HIGH_DIFFICULTY_CRITICAL_IMPORTANCE_MR = 5
HIGH_DIFFICULTY_FEATURE_MR = 5
HIGH_DIFFICULTY_BUG_MR = 5
NATIVE_BEAR_MR = 5
LINTER_BEAR_MR = 5
GENERIC_BEAR_MR = 5
