# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.IntegerField()),
                ('number_of_times', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('min_score', models.BigIntegerField()),
                ('max_score', models.BigIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('activities', models.ManyToManyField(to='gamification.Activity')),
                ('level', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.Level')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.Participant'),
        ),
    ]
