# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_times', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='b_activities',
            field=models.ManyToManyField(to='gamification.BadgeActivity'),
        ),
        migrations.AddField(
            model_name='participant',
            name='badges',
            field=models.ManyToManyField(to='gamification.Badge'),
        ),
    ]
